labels: []
body:
- type: markdown
  attributes:
    value: |
      ## Cleanup Crew Request Form
      If you are trying to convert a Scratch project to JavaScript using Leopard and something isn't working,
      the Leopard Mentors Cleanup Crew can help! Use the form below to explain the situation, and Leopard Mentors
      will reply with helpful advice. Be sure to check back later to read any comments they send!
- type: input
  id: scratch-project
  attributes:
    label: Scratch Project URL
    description: "A link to the Scratch project you are working with"
    placeholder: "https://scratch.mit.edu/projects/.../"
- type: input
  id: leopard-project
  attributes:
    label: Leopard Project URL
    description: "A link to the Leopard project that you need help cleaning up. **Please remember to click \"share\" on your project!**"
    placeholder: "https://leopardjs.com/projects/.../"
- type: checkboxes
  id: problem-type
  attributes:
    label: What kind of error(s) are you experiencing?
    options:
      - label: Leopard is failing to generate JavaScript code
      - label: The JavaScript code generated by Leopard doesn't work correctly
      - label: The JavaScript code generated by Leopard is confusing or needs improvement
      - label: Other
  validations:
    required: true
- type: textarea
  id: description
  attributes:
    label: Description of issue(s)
    description: |
      What is going wrong with your project? What have you tried on your own, and what specifically
      are you hoping the Leopard mentors can help you solve? Please provide as much **specific** information
      as you can.
  validations:
    required: true
